### PR TITLE
Add absent repos

### PR DESCRIPTION
**Pull request by genryxy**
Added items for absent repos in dropdown list
For artipie/artipie#895

### CODE REVIEW

**Review by g4s8 — APPROVED** [review]
@genryxy thanks

**Comment by genryxy** [comment]
@g4s8 could you please release a new version

**Comment by g4s8** [comment]
@rultor release, tag=`0.4.5`

**Comment by g4s8** [comment]
> @g4s8 could you please release a new version

@genryxy done: https://github.com/artipie/management-api/releases/tag/0.4.5

**Pull request merged**
